# helm/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
      service: weather
  template:
    metadata:
      labels:
        app: weather-app
        service: weather
    spec:
      containers:
        - name: weather-service
          image: urkoren/do19:1
          ports:
            - containerPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
      service: mail
  template:
    metadata:
      labels:
        app: weather-app
        service: mail
    spec:
      containers:
        - name: mail-service
          image: urkoren/mail_service:2
          ports:
            - containerPort: 5002

