apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mail-service-1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mail-service-1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mail-service-1
    spec:
      containers:
        - name: mail-service-1
          image: "{{ .Values.image.repository }}/{{ .Values.image.myimage }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
        - name: mail-service-2
          image: "{{ .Values.image.repository }}/{{ .Values.image.myimage2 }}:{{ .Values.image.tag2 }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}


