apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-service  # This must match the pod labels
  template:
    metadata:
      labels:
        app: weather-service  # This must match the service selector
        service: weather     # This matches the service selector in service.yaml
    spec:
      containers:
        - name: weather-service
          image: urkoren/do19:8
          ports:
            - containerPort: 5001
          env:
            - name: INGRESS_HOST
              valueFrom:
                configMapKeyRef:
                  name: weather-app-config
                  key: INGRESS_HOST

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
      service: mail  
  template:
    metadata:
      labels:
        app: weather-app  
        service: mail
    spec:
      containers:
        - name: mail-service
          image: urkoren/mail_service:3
          ports:
            - containerPort: 5002

