apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          # Existing path for the app service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-service
                port:
                  number: 5001

          # New path for the mail service
          - path: /mail-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mail-service
                port:
                  number: 5002

