apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather-app
    service: weather
spec:
  selector:
    app: weather-service  
    service: weather
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
  labels:
    app: weather-app
    service: mail
spec:
  selector:
    app: weather-app  
    service: mail
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP

