apiVersion: v1
kind: Service
metadata:
  name: app-service-1
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - port: 5001
      targetPort: 5001 

---
apiVersion: v1
kind: Service
metadata:
  name: app-service-2
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - port: 5002
      targetPort: 5002  

