apiVersion: v1
kind: Service
metadata:
  name: app-service-1
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - port: 5001
      targetPort: 5001  # Expose port 5001 for mail-service-1

---
apiVersion: v1
kind: Service
metadata:
  name: app-service-2
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - port: 5002
      targetPort: 5002  # Expose port 5002 for mail-service-2

