FROM docker:24.0.4-cli

# Install Python, pip, bash, git, curl, and AWS CLI
RUN apk add --no-cache python3 py3-pip bash git curl openssl aws-cli

# Install pylint and requests
RUN pip3 install pylint requests

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/

# Install Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Verify installations
RUN kubectl version --client && helm version

