FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip \
        curl \
        python3-venv \
        docker.io

RUN python3 -m venv venv && \
    /venv/bin/pip install pylint

COPY /var/run/docker.sock /var/run/docker.sock

RUN chmod 666 /var/run/docker.sock

USER jenkins

CMD ["bash"]
