version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    container_name: jenkins_container
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
volumes:
  jenkins_home:
