appName: weather-app
replicaCount: 4

image:
  repository: urkoren
  myimage: do19
  myimage2: mail_service
  tag: 1
  tag2: 2

service:
  name: app-service
  type: "ClusterIP"
  port1: 5001
  port2: 5002
  targetPort: 5001

