FROM python:3.9-slim AS builder
WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./*.py  .

EXPOSE 5002

CMD gunicorn --bind 0.0.0.0:5002 --workers=2 wsgi:app

