FROM python:3.9-slim AS  builder
WORKDIR /app

COPY ./requirements.txt .

RUN pip install -r requirements.txt \
    && rm requirements.txt


COPY ./app  .
FROM builder

WORKDIR /app

COPY --from=builder ./app .

EXPOSE 8001

CMD gunicorn --bind 0.0.0.0:8001 wsgi:app


